version: "3.9"

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./.db/postgres/volume:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: default
      POSTGRES_PASSWORD: 9yEumx4mEb
      POSTGRES_DB: default

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass 9QYVMZNxuSmPp1GyvNs38FKh4rqBMZfCMrCWkXlnmpSm
    ports:
      - "6379:6379"
    volumes:
      - ./.db/redis/volume:/data

  backend:
    build: backend
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - redis

  client:
    build: client
    ports:
      - '5173:5173'
