version: "3.9"

services:
  elasticsearch:
    image: elasticsearch:8.10.2
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ELASTIC_PASSWORD=Y3KgattXgebGXUd
    volumes:
      - ./.db/elasticsearch/volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./.db/postgres/volume:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: default
      POSTGRES_PASSWORD: 9yEumx4mEb
      POSTGRES_DB: default

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass 9QYVMZNxuSmPp1GyvNs38FKh4rqBMZfCMrCWkXlnmpSm
    ports:
      - "6379:6379"
    volumes:
      - ./.db/redis/volume:/data

  seaweedfs-master:
    image: chrislusf/seaweedfs
    ports:
      - "9333:9333"
      - "19333:19333"
      - "9324:9324"
    volumes:
      - ./.db/seaweedfs-master:/data
    command: "master -ip=master -ip.bind=0.0.0.0 -metricsPort=9324"

  seaweedfs-volume:
    image: chrislusf/seaweedfs
    ports:
      - "8082:8082"
      - "18080:18080"
      - "9325:9325"
    volumes:
      - ./.db/seaweedfs-volume:/data
    command: 'volume -mserver="seaweedfs-master:9333" -ip.bind=0.0.0.0 -port=8082  -metricsPort=9325'
    depends_on:
      - seaweedfs-master